"""Constants used by the Remora component."""
DOMAIN = "remora"
FILPILOTE = "filpilote"
FP = "fp"
RELAIS = "relais"
FNCT_RELAIS = "fnct_relais"
CONF_TEMP_SENSOR = "temp_sensor"
SERVICE_RESET = "reset"
